{% set name = "qiskit" %}
{% set version = "0.46.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-{{ version }}.tar.gz
  sha256: 7adc208d5fb8d2181ea0cfb1cfe4d6b93ca60b8337918b424ed434e29676b83f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - qiskit-terra ==0.46.0

test:
  imports:
    - qiskit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://qiskit.org/
  summary: Software for developing quantum computing programs
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
    - wshanks
