{% set name = "qiskit" %}
{% set version = "0.45.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-{{ version }}.tar.gz
  sha256: 7dbf61187d04881b8d6f89165b752bd0f318b74eacb9e102517b95d60cc658b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - qiskit-terra ==0.45.0

test:
  imports:
    - qiskit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://qiskit.org/
  summary: Software for developing quantum computing programs
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
    - wshanks
